{
 "title": "Docker Swarm - Performance",
 "tags": [
  "swarm",
  "performance"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(container_label_com_docker_swarm_service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources by Task (Swarm)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Allocations",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (\n  container_label_com_docker_swarm_task_name,\n  container_label_com_docker_swarm_task_id\n)(\n  (\n    container_spec_cpu_quota{\n      container_label_com_docker_swarm_service_name=~\"$service\"\n    }\n  )\n  /\n  (\n    container_spec_cpu_period{\n      container_label_com_docker_swarm_service_name=~\"$service\"\n    }\n  )\n)",
     "legendFormat": "cpu_alloc"
    },
    {
     "expr": "max by (\n  container_label_com_docker_swarm_service_name,\n  container_label_com_docker_swarm_task_name,\n  container_label_com_docker_swarm_task_id\n)(\n  container_spec_memory_limit_bytes{\n    container_label_com_docker_swarm_service_name=~\"$service\"\n  }\n)",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "CPU Max (Cores)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(\n  sum by (\n    container_label_com_docker_swarm_service_name,\n    container_label_com_docker_swarm_task_name,\n    container_label_com_docker_swarm_task_id\n  ) (\n    rate(container_cpu_usage_seconds_total{\n      container_label_com_docker_swarm_service_name=~\"$service\"\n    }[30s])\n  )\n[$__range:])",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}} {{container_label_com_docker_swarm_task_id}}"
    }
   ]
  },
  {
   "title": "Memory Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container_label_com_docker_swarm_task_name)(\n  max_over_time(\n    container_memory_working_set_bytes{\n      container_label_com_docker_swarm_service_name=~\"$service\"\n    }\n  [$__range:])\n) ",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "CPU Average (Cores)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "  avg by (\n    container_label_com_docker_swarm_service_name,\n    container_label_com_docker_swarm_task_name,\n    container_label_com_docker_swarm_task_id\n  ) (\n    rate(container_cpu_usage_seconds_total{\n      container_label_com_docker_swarm_service_name=~\"$service\"\n    }[$__range])\n  )\n\n\n\n\n",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}} {{container_label_com_docker_swarm_task_id}}"
    }
   ]
  },
  {
   "title": "Memory Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  avg_over_time(\n    container_memory_working_set_bytes{\n      container_label_com_docker_swarm_service_name=~\"$service\"\n    }\n  [$__range:])\n ",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}} {{container_label_com_docker_swarm_task_id}}"
    }
   ]
  },
  {
   "title": "CPU % by Task",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name, container_label_com_docker_swarm_task_name) (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"$service\"}[$__rate_interval])) * 100",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}} - {{container_label_com_docker_swarm_task_name}}"
    }
   ]
  },
  {
   "title": "Memory % by Task",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name, container_label_com_docker_swarm_task_name) (container_memory_working_set_bytes{container_label_com_docker_swarm_service_name=~\"$service\"} / container_spec_memory_limit_bytes{container_label_com_docker_swarm_service_name=~\"$service\"}) * 100",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}} - {{container_label_com_docker_swarm_task_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage (Cores) by Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_task_name)(\n  rate(container_cpu_usage_seconds_total{\n    container_label_com_docker_swarm_service_name=~\"$service\"\n  }[$__range])\n)",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }} - {{ container_label_com_docker_swarm_task_name}} "
    }
   ]
  },
  {
   "title": "Memory Bytes by Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "\n    container_memory_working_set_bytes{\n      container_label_com_docker_swarm_service_name=~\"$service\"\n    }\n  \n ",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }} - {{ container_label_com_docker_swarm_task_name }}"
    }
   ]
  },
  { "title": "Resources by Service (Swarm)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Services Summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name) (container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\"$service\"} / container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\"$service\"})",
     "legendFormat": "cpu_total"
    },
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name) (container_spec_memory_limit_bytes{container_label_com_docker_swarm_service_name=~\"$service\"})",
     "legendFormat": "memory_total"
    },
    {
     "expr": "count by (container_label_com_docker_swarm_service_name) (container_last_seen{container_label_com_docker_swarm_service_name=~\"$service\"})",
     "legendFormat": "task_count"
    }
   ]
  },
  {
   "title": "CPU Max (Cores)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(\n  sum by (\n    container_label_com_docker_swarm_service_name,\n\n  ) (\n    rate(container_cpu_usage_seconds_total{\n      container_label_com_docker_swarm_service_name=~\"$service\"\n    }[30s])\n  )\n[$__range:])",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Memory Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name)(\n  max_over_time(\n    container_memory_working_set_bytes{\n      container_label_com_docker_swarm_service_name=~\"$service\"\n    }\n  [$__range:])\n) ",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "CPU Average (Cores)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (container_label_com_docker_swarm_service_name)(\n    rate(container_cpu_usage_seconds_total{\n      container_label_com_docker_swarm_service_name=~\"$service\"\n    }[$__range])\n  )\n[$__range:])",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Memory Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum by (container_label_com_docker_swarm_service_name)(avg_over_time(\n    container_memory_working_set_bytes{\n      container_label_com_docker_swarm_service_name=~\"$service\"\n    }\n  [$__range:]))\n ",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "CPU % by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name) (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"$service\"}[$__rate_interval])) * 100",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Memory % by Service",
   "type": "timeseries",
   "description": "Memory % by Service",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name) (container_memory_working_set_bytes{container_label_com_docker_swarm_service_name=~\"$service\"} / container_spec_memory_limit_bytes{container_label_com_docker_swarm_service_name=~\"$service\"}) * 100",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "CPU Usage (Cores) by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_task_name)(\n  rate(container_cpu_usage_seconds_total{\n    container_label_com_docker_swarm_service_name=~\"$service\"\n  }[$__range])\n)",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }} - {{ container_label_com_docker_swarm_task_name}} "
    }
   ]
  },
  {
   "title": "Memory Bytes by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name) (container_memory_working_set_bytes{container_label_com_docker_swarm_service_name=~\"$service\"})",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  }
 ]
}