{
 "title": "General - Performance Overview",
 "tags": [
  "performance",
  "overview"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated, exported_job)"
    }
   },
   {
    "name": "task_group",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated,task_group)"
    }
   },
   {
    "name": "scenario",
    "query": {
     "query": "label_values(k6_http_reqs_total, scenario)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(traefik_service_requests_total, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Nomad - Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cpu Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_job, task_group) (avg_over_time(  nomad_client_allocs_cpu_total_ticks{exported_job=~\"$job\", task_group=~\"$task_group\"}[$__range]) )",
     "legendFormat": " {{exported_job}}  {{task_group}}"
    }
   ]
  },
  {
   "title": "Memory Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nsum by (exported_job, task_group) (avg_over_time(  nomad_client_allocs_memory_usage{exported_job=~\"$job\", task_group=~\"$task_group\"}[$__range]) )",
     "legendFormat": " {{exported_job}} {{ task_group }}"
    }
   ]
  },
  {
   "title": "Cpu Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_job, task_group) (max_over_time(  nomad_client_allocs_cpu_total_ticks{exported_job=~\"$job\", task_group=~\"$task_group\"}[$__range]) )\n\n",
     "legendFormat": "{{exported_job}} {{task_group}}"
    }
   ]
  },
  {
   "title": "Memory Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_job, task_group) (max_over_time(  nomad_client_allocs_memory_usage{exported_job=~\"$job\", task_group=~\"$task_group\"}[$__range]) )",
     "legendFormat": " {{exported_job}}  {{task_group}}"
    }
   ]
  },
  { "title": "K6 - Load Test Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Taxa Sucesso",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(increase(k6_http_reqs_total{scenario=~\"$scenario\", expected_response=\"true\"}[$__range])) / (sum(increase(k6_http_reqs_total{scenario=~\"$scenario\"}[$__range])) + (sum(increase(k6_dropped_iterations_total{scenario=~\"$scenario\"}[$__range])) or vector(0))))) * 100",
     "legendFormat": "Taxa Sucesso"
    }
   ]
  },
  {
   "title": "Virtual Users (VUs)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum by (scenario) (\n  avg_over_time(k6_vus[1m])\n)",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "K6 Report",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "avg by (scenario) (\n  last_over_time(\n    k6_http_req_duration_avg{scenario=~\"$scenario\"}[$__range]\n  )\n) * 1000"
    },
    {
     "expr": "avg by (scenario) (\n  last_over_time(\n    k6_http_req_duration_p95{scenario=~\"$scenario\"}[$__range]\n  )\n) * 1000"
    }
   ]
  },
  { "title": "Traefik - Gateway Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Taxa Sucesso",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(traefik_service_requests_total{service=~\"$service\",code=~\"2..\"}[$__range])) / (sum(rate(traefik_service_requests_total{service=~\"$service\"}[$__range])) or vector(1))) * 100",
     "legendFormat": "Taxa Sucesso"
    }
   ]
  },
  {
   "title": "Reqs Sucesso",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(traefik_service_requests_total{service=~\"$service\", code=~\"[23]..\"}[$__range])\n) by (service)",
     "legendFormat": "{{service}} - Reqs Sucesso"
    }
   ]
  },
  {
   "title": "Reqs Erro",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(traefik_service_requests_total{service=~\"$service\", code=~\"[45]..\"}[$__range])\n) by (service)",
     "legendFormat": "{{service}} - Reqs Erro"
    }
   ]
  },
  {
   "title": "Tempo Médio (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(traefik_service_request_duration_seconds_sum{service=~\"$service\"}[1m]))\n  by (service)\n)\n/\n(\n  sum(rate(traefik_service_request_duration_seconds_count{service=~\"$service\"}[1m]))\n  by (service)\n)\n* 1000",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Reqs Sucesso",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=~\"$service\", code=~\"[23]..\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Reqs Erro",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=~\"$service\", code=~\"5..\"}[1m])) by (service)",
     "legendFormat": "{{service}} 5xx"
    },
    {
     "expr": "sum(increase(traefik_service_requests_total{service=~\"$service\", code=~\"4..\"}[1m])) by (service)",
     "legendFormat": "{{service}} 4xx"
    }
   ]
  },
  {
   "title": "RPS Médio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "P95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traefik_service_request_duration_seconds_bucket{service=~\"$service\"}[1m])) by (service, le)) * 1000",
     "legendFormat": "{{service}} P95"
    }
   ]
  },
  {
   "title": "P99 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(traefik_service_request_duration_seconds_bucket{service=~\"$service\"}[1m])) by (service, le)) * 1000",
     "legendFormat": "{{service}} P99"
    }
   ]
  },
  { "title": "K6 Detailed Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Taxa Sucesso",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(increase(k6_http_reqs_total{scenario=~\"$scenario\", expected_response=\"true\"}[$__range])) / (sum(increase(k6_http_reqs_total{scenario=~\"$scenario\"}[$__range])) + (sum(increase(k6_dropped_iterations_total{scenario=~\"$scenario\"}[$__range])) or vector(0))))) * 100",
     "legendFormat": "Taxa Sucesso"
    }
   ]
  },
  {
   "title": "Reqs Sucesso",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(k6_http_reqs_total{scenario=~\"$scenario\", expected_response=\"true\"}[1m])) by (scenario)",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Reqs Erro",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(k6_dropped_iterations_total{scenario=~\"$scenario\", expected_response=\"true\"}[1m])) by (scenario)",
     "legendFormat": "{{scenario}} Dropped Iterations"
    },
    {
     "expr": "sum(increase(k6_http_reqs_total{scenario=~\"$scenario\", expected_response=\"false\"}[1m])) by (scenario)",
     "legendFormat": "{{scenario}} HTTP Req Failed"
    }
   ]
  },
  {
   "title": "Tempo Médio (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (scenario) (\n  avg_over_time(\n    k6_http_req_duration_avg{scenario=~\"$scenario\"}[1m]\n  )\n) * 1000",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "P95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (scenario) (\n  avg_over_time(\n    k6_http_req_duration_p95{scenario=~\"$scenario\"}[1m]\n  )\n) * 1000",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "P99 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (scenario) (\n  avg_over_time(\n    k6_http_req_duration_p99{scenario=~\"$scenario\"}[1m]\n  )\n) * 1000",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "RPS Médio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{scenario=~\"$scenario\"}[1m])) by (scenario)",
     "legendFormat": "{{scenario}}"
    }
   ]
  }
 ]
}