{
 "title": "Traefik - Performance Metrics",
 "tags": [
  "traefik",
  "performance",
  "proxy"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traefik_service_requests_total, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Taxa Sucesso",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(traefik_service_requests_total{service=~\"$service\",code=~\"2..\"}[$__range])) / (sum(rate(traefik_service_requests_total{service=~\"$service\"}[$__range])) or vector(1))) * 100",
     "legendFormat": "Taxa Sucesso"
    }
   ]
  },
  {
   "title": "Traefik Report",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(\n  sum(rate(traefik_service_request_duration_seconds_sum{service=~\"$service\"}[$__range]))\n  by (service)\n)\n/\n(\n  sum(rate(traefik_service_request_duration_seconds_count{service=~\"$service\"}[$__range]))\n  by (service)\n)\n* 1000"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traefik_service_request_duration_seconds_bucket{service=~\"$service\"}[$__range])) by (service, le)) * 1000"
    },
    {
     "expr": "sum by (service) (\n  increase(traefik_service_requests_total{service=~\"$service\"}[$__range])\n)"
    },
    {
     "expr": "sum by (service) (increase(traefik_service_requests_total{service=~\"$service\",code=~\"[45]..\"}[$__range]))"
    },
    {
     "expr": "(\n  sum by (service) (\n    rate(traefik_service_requests_total{service=~\"$service\", code=~\"[45]..\"}[$__range])\n  )\n  /\n  (\n    sum by (service) (\n      rate(traefik_service_requests_total{service=~\"$service\"}[$__range])\n    )\n    or vector(1)\n  )\n) * 100\n"
    }
   ]
  },
  {
   "title": "RPS Médio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Reqs Sucesso",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=~\"$service\", code=~\"[23]..\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Reqs Erro",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=~\"$service\", code=~\"5..\"}[1m])) by (service)",
     "legendFormat": "{{service}} 5xx Errors"
    },
    {
     "expr": "sum(increase(traefik_service_requests_total{service=~\"$service\", code=~\"4..\"}[1m])) by (service)",
     "legendFormat": "{{service}} 4xx Errors"
    }
   ]
  },
  {
   "title": "P95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traefik_service_request_duration_seconds_bucket{service=~\"$service\"}[1m])) by (service, le)) * 1000",
     "legendFormat": "{{service}} P95"
    }
   ]
  },
  {
   "title": "P99 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(traefik_service_request_duration_seconds_bucket{service=~\"$service\"}[1m])) by (service, le)) * 1000",
     "legendFormat": "{{service}} P99"
    }
   ]
  },
  {
   "title": "Tempo Médio (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(traefik_service_request_duration_seconds_sum{service=~\"$service\"}[1m]))\n  by (service)\n)\n/\n(\n  sum(rate(traefik_service_request_duration_seconds_count{service=~\"$service\"}[1m]))\n  by (service)\n)\n* 1000",
     "legendFormat": "{{service}} Avg"
    }
   ]
  }
 ]
}