{
 "title": "PostgreSQL Overview",
 "tags": [
  "postgres",
  "database",
  "infra"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes{datname=\"benchmark\"})"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=\"benchmark\"})"
    }
   ]
  },
  {
   "title": "Transactions Commited",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_xact_commit{datname=\"benchmark\"})"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_deadlocks{datname=\"benchmark\"})"
    }
   ]
  },
  {
   "title": "Transactions Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"benchmark\"}[1m])",
     "legendFormat": "Commits"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"benchmark\"}[1m])",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blks_hit{datname=\"benchmark\"}[1m])) / (sum(rate(pg_stat_database_blks_hit{datname=\"benchmark\"}[1m])) + sum(rate(pg_stat_database_blks_read{datname=\"benchmark\"}[1m]))) * 100",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  {
   "title": "Tuples Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"benchmark\"}[1m])",
     "legendFormat": "Inserted"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{datname=\"benchmark\"}[1m])",
     "legendFormat": "Updated"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{datname=\"benchmark\"}[1m])",
     "legendFormat": "Deleted"
    },
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"benchmark\"}[1m])",
     "legendFormat": "Fetched"
    }
   ]
  }
 ]
}