flyway.url=jdbc:postgresql://demo_postgres:5432/demo_db
flyway.user=demo_user
flyway.password=demo_password
flyway.cleanDisabled=false
flyway.baselineOnMigrate=true
flyway.baselineVersion=0
flyway.baselineVersion=0
