{
 "title": "KPIs - Python",
 "tags": [
  "stack",
  "python",
  "kpi"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=~\"python-.*\"}, container_label_com_docker_compose_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage (cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=~\"$service\"}[1m]))",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Memory usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (container_memory_usage_bytes{container_label_com_docker_compose_service=~\"$service\"}) / 1024 / 1024",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "HTTP requests (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_requests_total{job=~\"$service\", uri!~\"/actuator.*|/metrics\"}[1m]))",
     "legendFormat": "{{job}} {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Latency (P95, P99) - ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, job) ((rate(http_request_duration_seconds_bucket{job=~\"$service\", uri!~\"/actuator.*|/metrics\"}[1m])))) * 1000",
     "legendFormat": "{{job}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, job) ((rate(http_request_duration_seconds_bucket{job=~\"$service\", uri!~\"/actuator.*|/metrics\"}[1m])))) * 1000",
     "legendFormat": "{{job}} P99"
    }
   ]
  },
  {
   "title": "Python Process Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job) (python_info{job=~\"$service\"})",
     "legendFormat": "{{job}} version"
    }
   ]
  },
  {
   "title": "HTTP Latency Average per endpoint - ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (handler, job) (rate(http_request_duration_seconds_sum{job=~\"$service\", handler!~\"/actuator.*|/metrics\"}[1m])) / sum by (handler, job) (rate(http_request_duration_seconds_count{job=~\"$service\", handler!~\"/actuator.*|/metrics\"}[1m])) * 1000",
     "legendFormat": "{{job}} {{handler}}"
    }
   ]
  },
  {
   "title": "App Errors (4xx|5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (job) (  increase(http_requests_total{job=~\"$service\", handler!~\"/actuator.*|/metrics\", path!~\"/actuator.*|/metrics\", status=~\"4..|5..\"}[1m]))",
     "legendFormat": "{{job}} errors"
    }
   ]
  }
 ]
}