{
 "title": "Apps - Load Test Performance",
 "tags": [
  "apps",
  "loadtest",
  "performance"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(up{job=~\".*-(monolith|gateway)\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=~\"$service.*\"}[1m])) by (container_label_com_docker_compose_service)",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (container_memory_working_set_bytes{container_label_com_docker_compose_service=~\"$service.*\"}) / 1024 / 1024",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage (cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(process_cpu_seconds_total{job=~\"$service\"}[1m]) or process_cpu_usage{job=~\"$service\"})",
     "legendFormat": "{{job}} CPU Usage"
    }
   ]
  },
  {
   "title": "Process Memory (RSS) (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum by (job) (process_resident_memory_bytes{job=~\"$service\"}) / 1024 / 1024",
     "legendFormat": "{{job}} RSS"
    }
   ]
  },
  {
   "title": "HTTP requests (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_requests_total{job=~\"$service\" , uri!~\"/actuator.*|/metrics\"}[1m]) or rate(http_server_requests_seconds_count{job=~\"$service\", uri!~\"/actuator.*|/metrics\"}[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Call Latency Average per endpoint - ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (path, handler, job) (rate(http_request_duration_seconds_sum{job=~\"$service\", handler!~\"/actuator.*|/metrics\", path!~\"/actuator.*|/metrics\"}[1m])) / sum by (path, handler, job) (rate(http_request_duration_seconds_count{job=~\"$service\", handler!~\"/actuator.*|/metrics\", path!~\"/actuator.*|/metrics\"}[1m])) * 1000",
     "legendFormat": "{{job}} {{path}} {{handler}}"
    },
    {
     "expr": "sum by (uri, job) (rate(http_server_requests_seconds_sum{job=~\"$service\", uri!~\"/actuator.*|/metrics\"}[1m])) / sum by (uri, job) (rate(http_server_requests_seconds_count{job=~\"$service\", uri!~\"/actuator.*|/metrics\"}[1m])) * 1000",
     "legendFormat": "{{job}} {{uri}}"
    }
   ]
  },
  {
   "title": "App Latency (P95) - ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, job) (rate(http_request_duration_seconds_bucket{job=~\"$service\", path!~\"/actuator.*|/metrics\"}[1m]) or rate(http_server_requests_seconds_bucket{job=~\"$service\", uri!~\"/actuator.*|/metrics\"}[1m]))) * 1000",
     "legendFormat": "{{job}} P95"
    }
   ]
  },
  {
   "title": "App Latency (P99) - ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, job) (rate(http_request_duration_seconds_bucket{job=~\"$service\", path!~\"/actuator.*|/metrics\"}[1m]) or rate(http_server_requests_seconds_bucket{job=~\"$service\", uri!~\"/actuator.*|/metrics\"}[1m]))) * 1000",
     "legendFormat": "{{job}} P99"
    }
   ]
  },
  {
   "title": "App Success (2xx |3xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (job) (  increase(http_requests_total{job=~\"$service\", handler!~\"/actuator.*|/metrics\", path!~\"/actuator.*|/metrics\", status=~\"2..|3..\"}[1m]) or increase(http_server_requests_seconds_count{job=~\"$service\", uri!~\"/actuator.*|/metrics\", status=~\"2..|3..\"}[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "App Errors (4xx|5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by (job) (  increase(http_requests_total{job=~\"$service\", handler!~\"/actuator.*|/metrics\", path!~\"/actuator.*|/metrics\", status=~\"4..|5..\"}[1m]) or increase(http_server_requests_seconds_count{job=~\"$service\", uri!~\"/actuator.*|/metrics\", status=~\"4..|5..\"}[1m]))",
     "legendFormat": "{{job}} errors"
    }
   ]
  }
 ]
}