# O Liquibase Docker irá enxergar o hostname 'demo_postgres' dentro da rede do docker-compose
changeLogFile=changelog/db.changelog-master.sql
url=jdbc:postgresql://demo_postgres:5432/demo_db
username=demo_user
password=demo_password
driver=org.postgresql.Driver
