
server:
  port: 8081
management:
  endpoints:
    jmx.exposure.include: "health,info,mappings"
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
spring:
  security:
    oauth2: 
      resourceserver:
        jwt: 
          issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
      client:
        provider: 
          keycloak:
            issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid