services:
  golang-monolith:
    image: benchmark-stacks/golang-monolith:1.0
    environment:
      DB_HOST: pgbouncer
      DB_PORT: 6432
      DB_USER: golang_user
      DB_PASSWORD: golang_pass
      DB_NAME: benchmark
      DB_MAX_POOL_SIZE: 120
    networks:
      - stacks_default
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.5'
          memory: 256M
        reservations:
          cpus: '1.5'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.golang-monolith.rule=PathPrefix(`/`)"
        - "traefik.http.routers.golang-monolith.entrypoints=golang"
        - "traefik.http.services.golang-monolith.loadbalancer.server.port=3000"

networks:
  stacks_default:
    external: true
