services:
  webflux-monolith:
    image: benchmark-stacks/java-webflux-monolith:1.0
    environment:
      DB_HOST: pgbouncer
      DB_PORT: 6432
      DB_USER: java_webflux_user
      DB_PASSWORD: java_webflux_pass
      DB_NAME: benchmark
      DB_MAX_POOL_SIZE: 120
    networks:
      - stacks_default
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.5'
          memory: 256M
        reservations:
          cpus: '1.5'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.webflux-monolith.rule=PathPrefix(`/`)"
        - "traefik.http.routers.webflux-monolith.entrypoints=webflux"
        - "traefik.http.services.webflux-monolith.loadbalancer.server.port=3002"

networks:
  stacks_default:
    external: true
