services:
  nestjs-monolith:
    image: benchmark-stacks/nestjs-monolith:1.0
    environment:
      DB_HOST: pgbouncer
      DB_PORT: 6432
      DB_USER: nodejs_user
      DB_PASSWORD: nodejs_pass
      DB_NAME: benchmark
      DB_MAX_POOL_SIZE: 100
    networks:
      - stacks_default
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 1024M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nestjs-monolith.rule=PathPrefix(`/`)"
        - "traefik.http.routers.nestjs-monolith.entrypoints=nestjs"
        - "traefik.http.services.nestjs-monolith.loadbalancer.server.port=3001"

networks:
  stacks_default:
    external: true
