services:
  fpm-monolith:
    image: benchmark-stacks/php-laravel-fpm-monolith:1.0
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: pgbouncer
      DB_PORT: 6432
      DB_DATABASE: benchmark
      DB_USERNAME: php_fpm_user
      DB_PASSWORD: php_fpm_pass
      APP_KEY: "base64:u8MvK+1512zU2m6XvP3Yv1rK8Z5o8z8k9u0u1u2u3u4="
      SESSION_DRIVER: array
      APP_ENV: production
      APP_DEBUG: "false"
      FPM_MAX_CHILDREN: 4
    networks:
      - stacks_default
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M
        reservations:
          cpus: '2.0'
          memory: 2048M
# 8 replicas e cpus 1.0 passou perto
  fpm-nginx:
    image: nginx:alpine
    volumes:
      - ../../apps/php-laravel-fpm/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ../../apps/php-laravel-fpm:/var/www/html
    networks:
      - stacks_default
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.512'
          memory: 512M
        reservations:
          cpus: '0.512'
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.fpm-monolith.rule=PathPrefix(`/`)"
        - "traefik.http.routers.fpm-monolith.entrypoints=fpm"
        - "traefik.http.services.fpm-monolith.loadbalancer.server.port=80"

networks:
  stacks_default:
    external: true
