services:
  python-monolith:
    image: benchmark-stacks/python-fastapi-monolith:1.0
    environment:
      DB_URL: "postgresql+asyncpg://python_fastapi_user:python_fastapi_pass@pgbouncer:6432/benchmark"
      DB_MAX_POOL_SIZE: 100
      WORKERS: 3
    networks:
      - stacks_default
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 1024M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.python-monolith.rule=PathPrefix(`/`)"
        - "traefik.http.routers.python-monolith.entrypoints=python"
        - "traefik.http.services.python-monolith.loadbalancer.server.port=8000"

networks:
  stacks_default:
    external: true
