services:
  rust-monolith:
    image: benchmark-stacks/rust-monolith:1.0
    environment:
      DB_HOST: pgbouncer
      DB_PORT: 6432
      DB_USER: rust_user
      DB_PASSWORD: rust_pass
      DB_NAME: benchmark
      DB_MAX_POOL_SIZE: 120
    networks:
      - stacks_default
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 1024M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rust-monolith.rule=PathPrefix(`/`)"
        - "traefik.http.routers.rust-monolith.entrypoints=rust"
        - "traefik.http.services.rust-monolith.loadbalancer.server.port=3000"

networks:
  stacks_default:
    external: true
