{
 "title": "K6 - Load Test Performance",
 "tags": [
  "k6",
  "loadtest",
  "performance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "scenario",
    "label": "Scenario",
    "query": {
     "query": "label_values(k6_http_reqs_total, scenario)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Taxa Sucesso",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(increase(k6_http_reqs_total{scenario=~\"$scenario\", expected_response=\"true\"}[$__range])) / (sum(increase(k6_http_reqs_total{scenario=~\"$scenario\"}[$__range])) + (sum(increase(k6_dropped_iterations_total{scenario=~\"$scenario\"}[$__range])) or vector(0))))) * 100",
     "legendFormat": "Taxa Sucesso"
    }
   ]
  },
  {
   "title": "K6 Report",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by (scenario) (\n  last_over_time(\n    k6_http_req_duration_avg{scenario=~\"$scenario\"}[$__range]\n  )\n) * 1000"
    },
    {
     "expr": "avg by (scenario) (\n  last_over_time(\n    k6_http_req_duration_p95{scenario=~\"$scenario\"}[$__range]\n  )\n) * 1000"
    },
    {
     "expr": "sum by (scenario) (increase(k6_http_reqs_total{scenario=~\"$scenario\"}[$__range]))"
    },
    {
     "expr": "sum by (scenario) (increase(k6_http_reqs_total{scenario=~\"$scenario\", expected_response=\"false\"}[$__range]))"
    },
    {
     "expr": "sum by (scenario) (k6_threshold_trend_total{scenario=~\"$scenario\"})"
    },
    {
     "expr": "sum by (scenario) (k6_check_failures_total{scenario=~\"$scenario\"})"
    }
   ]
  },
  {
   "title": "Virtual Users (VUs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (scenario) (\n  avg_over_time(k6_vus[1m])\n)",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "RPS Médio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{scenario=~\"$scenario\"}[1m])) by (scenario)",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Reqs Sucesso",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(k6_http_reqs_total{scenario=~\"$scenario\", expected_response=\"true\"}[1m])) by (scenario)",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Reqs Erro",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(k6_dropped_iterations_total{scenario=~\"$scenario\", expected_response=\"true\"}[1m])) by (scenario)",
     "legendFormat": "{{scenario}} Dropped Iterations"
    },
    {
     "expr": "sum(increase(k6_http_reqs_total{scenario=~\"$scenario\", expected_response=\"false\"}[1m])) by (scenario)",
     "legendFormat": "{{scenario}} HTTP Req Failed"
    }
   ]
  },
  {
   "title": "P95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (scenario) (\n  avg_over_time(\n    k6_http_req_duration_p95{scenario=~\"$scenario\"}[1m]\n  )\n) * 1000",
     "legendFormat": "{{scenario}} P95"
    }
   ]
  },
  {
   "title": "P99 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (scenario) (\n  avg_over_time(\n    k6_http_req_duration_p99{scenario=~\"$scenario\"}[1m]\n  )\n) * 1000",
     "legendFormat": "{{scenario}} P99"
    }
   ]
  },
  {
   "title": "Tempo Médio (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (scenario) (\n  avg_over_time(\n    k6_http_req_duration_avg{scenario=~\"$scenario\"}[1m]\n  )\n) * 1000",
     "legendFormat": "{{scenario}} {{name}}"
    }
   ]
  }
 ]
}