{
 "title": "Nomad - Performance Metrics",
 "tags": [
  "nomad",
  "performance",
  "proxy"
 ],
 "time": { "from": "2026-02-04T13:02:05.218Z", "to": "2026-02-04T13:05:13.613Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated,exported_job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources by task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Allocations",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "nomad_client_allocs_cpu_allocated{exported_job=~\"$job\"} * 1000000",
     "legendFormat": "cpu"
    },
    {
     "expr": "nomad_client_allocs_memory_allocated{exported_job=~\"$job\"}",
     "legendFormat": "memory"
    },
    {
     "expr": "nomad_client_allocs_memory_max_usage{exported_job=~\"$job\"}",
     "legendFormat": "memory max"
    }
   ]
  },
  {
   "title": "Cpu Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(\n  nomad_client_allocs_cpu_total_ticks{exported_job=~\"$job\"}[$__range]\n)",
     "legendFormat": " {{exported_job}} - {{task}}"
    }
   ]
  },
  {
   "title": "Cpu Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  nomad_client_allocs_cpu_total_ticks{exported_job=~\"$job\"}[$__range]\n)",
     "legendFormat": " {{exported_job}} - {{task}}"
    }
   ]
  },
  {
   "title": "Memory Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(\n  nomad_client_allocs_memory_usage{exported_job=~\"$job\"}[$__range]\n)",
     "legendFormat": " {{exported_job}} - {{task}}"
    }
   ]
  },
  {
   "title": "Memory Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  nomad_client_allocs_memory_usage{exported_job=~\"$job\"}[$__range]\n)",
     "legendFormat": " {{exported_job}} - {{task}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nomad_client_allocs_cpu_total_percent{exported_job=~\"$job\"}",
     "legendFormat": "{{ exported_job }} - {{ task_group }} - {{ task }} - {{ instance }} - {{ alloc_id }} Mhz"
    }
   ]
  },
  {
   "title": "CPU Ticks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "nomad_client_allocs_cpu_total_ticks{exported_job=~\"$job\"} * 1000000",
     "legendFormat": "{{ exported_job }} - {{ task_group }} - {{ task }} - {{ instance }} - {{ alloc_id }} Mhz"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(nomad_client_allocs_memory_usage{exported_job=~\"$job\"}\n- \nnomad_client_allocs_memory_cache{exported_job=~\"$job\"})\n/\nnomad_client_allocs_memory_allocated{exported_job=~\"$job\"} * 100",
     "legendFormat": "{{ exported_job }} - {{ task_group }} - {{ task }} - {{ instance }} - {{ alloc_id }}"
    }
   ]
  },
  {
   "title": "Memory Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(nomad_client_allocs_memory_usage{exported_job=~\"$job\"}\n- \nnomad_client_allocs_memory_cache{exported_job=~\"$job\"})",
     "legendFormat": "{{ exported_job }} - {{ task_group }} - {{ task }} - {{ instance }} - {{ alloc_id }}"
    }
   ]
  },
  { "title": "Resources by Job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Allocacoes Agregadas por Job",
   "type": "table",
   "description": "Tabela com CPU e Memory agregados por job",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (exported_job) (nomad_client_allocs_cpu_allocated{exported_job=~\"$job\"} * 1000000)",
     "legendFormat": "cpu_total"
    },
    {
     "expr": "sum by (exported_job) (nomad_client_allocs_memory_allocated{exported_job=~\"$job\"})",
     "legendFormat": "memory_total"
    },
    {
     "expr": "count by (exported_job) (nomad_client_allocs_cpu_allocated{exported_job=~\"$job\"})",
     "legendFormat": "alloc_count"
    }
   ]
  },
  {
   "title": "Cpu Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_job) (max_over_time(  nomad_client_allocs_cpu_total_ticks{exported_job=~\"$job\"}[$__range]) )",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Cpu Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_job) (avg_over_time(  nomad_client_allocs_cpu_total_ticks{exported_job=~\"$job\"}[$__range]) )",
     "legendFormat": " {{exported_job}}"
    }
   ]
  },
  {
   "title": "Memory Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_job) (max_over_time(  nomad_client_allocs_memory_usage{exported_job=~\"$job\"}[$__range]) )",
     "legendFormat": " {{exported_job}}"
    }
   ]
  },
  {
   "title": "Memory Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_job) (avg_over_time(  nomad_client_allocs_memory_usage{exported_job=~\"$job\"}[$__range]) )",
     "legendFormat": " {{exported_job}}"
    }
   ]
  },
  {
   "title": "CPU % Agregado por Job",
   "type": "timeseries",
   "description": "CPU % agregado por job",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (exported_job) (nomad_client_allocs_cpu_total_percent{exported_job=~\"$job\"})",
     "legendFormat": "{{ exported_job }}"
    }
   ]
  },
  {
   "title": "CPU Total (MHz) Agregado por Job",
   "type": "timeseries",
   "description": "CPU Total (MHz) agregado por job",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum by (exported_job) (nomad_client_allocs_cpu_total_ticks{exported_job=~\"$job\"} * 1000000)",
     "legendFormat": "{{ exported_job }}"
    }
   ]
  },
  {
   "title": "Memory % Agregado por Job",
   "type": "timeseries",
   "description": "Memory % agregado por job",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (exported_job) ((nomad_client_allocs_memory_usage{exported_job=~\"$job\"} - nomad_client_allocs_memory_cache{exported_job=~\"$job\"}) / nomad_client_allocs_memory_allocated{exported_job=~\"$job\"} * 100)",
     "legendFormat": "{{ exported_job }}"
    }
   ]
  },
  {
   "title": "Memory Total (GB) Agregado por Job",
   "type": "timeseries",
   "description": "Memory Total (GB) agregado por job",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (exported_job) ((nomad_client_allocs_memory_usage{exported_job=~\"$job\"} - nomad_client_allocs_memory_cache{exported_job=~\"$job\"}))",
     "legendFormat": "{{ exported_job }}"
    }
   ]
  }
 ]
}