{
 "title": "K6 - Load Test Performance",
 "tags": [
  "k6",
  "loadtest",
  "performance"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "scenario",
    "label": "Scenario",
    "query": {
     "query": "label_values(k6_http_reqs_total, scenario)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Virtual Users (VUs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(k6_vus) by (scenario)", "legendFormat": "{{scenario}}" }
   ]
  },
  {
   "title": "HTTP Request (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{scenario=~\"$scenario\"}[1m])) by (scenario)",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (P95) - ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(k6_http_req_duration_p95{scenario=~\"$scenario\"}) by (scenario) * 1000",
     "legendFormat": "{{scenario}} P95"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (P99) - ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(k6_http_req_duration_p99{scenario=~\"$scenario\"}) by (scenario) * 1000",
     "legendFormat": "{{scenario}} P99"
    }
   ]
  },
  {
   "title": "HTTP Success (2xx |3xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(k6_http_reqs_total{scenario=~\"$scenario\", expected_response=\"true\"}[1m])) by (scenario)",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "K6 HTTP Errors (dropped interations)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (scenario) ( increase(k6_dropped_iterations_total[1m]))",
     "legendFormat": "{{scenario}} errors"
    }
   ]
  },
  {
   "title": "Call Duration Average ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (tag_target, tag_endpoint) (  k6_http_req_duration_avg)",
     "legendFormat": "{{scenario}} {{name}}"
    },
    {
     "expr": "sum by (url, scenario) (rate(k6_http_req_duration_sum{scenario=~\"$scenario\", url!~\"/actuator.*|/metrics\"}[1m])) / sum by (url, scenario) (rate(k6_http_req_duration_count{scenario=~\"$scenario\", url!~\"/actuator.*|/metrics\"}[1m])) * 1000",
     "legendFormat": "{{scenario}} {{url}}"
    }
   ]
  },
  {
   "title": "K6 Request Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (scenario, tag_target) (  k6_http_req_failed_rate  *  rate(k6_http_reqs_total[1m])) * 60",
     "legendFormat": "{{scenario}} errors"
    }
   ]
  }
 ]
}